### PR TITLE
Unity xr 544 draft Pull Request

### PR DESCRIPTION
**Pull request by WilliamGoesGit**
VR isn't working yet.

### CODE REVIEW

**Comment by koschke** [comment]
@WilliamGoesGit Please make sure that your commit messages are in English. Your last ones aren't.

**Comment by koschke** [comment]
@Yvo02 Please make sure that your commit messages are informative. Your last ones aren't ("update").

**Comment by falko17** [comment]
Please note additionally that, as described in the CI, you will have to rebase the branch to get rid of the non-LFS assets outside the `Plugins/` folder from the commit history. During this rebase step, you could also reword the commit messages to be in German.

**Comment by koschke** [comment]
This PR has not received any changes for a very long time. I am deleting it to clean up, but the branch will continue to exist in case something were needed. Maybe we start from scratch when migrating to the CC4 avatars.

**Pull request closed without merging**
