### PR TITLE
764 make helpsystem work again and provide additional content

### LINKED ISSUE #764: Make HelpSystem work again and provide additional content
Seems like the HelpSystem stopped working at some point. This should be fixed. 

There is also need for more content and updated versions of existing videos.

### PR DESCRIPTION
**Pull request by SarahAugustinowski**
This should close #764 and make the HelpSystem work again. For that an empty "HelpSystem" with the follwing scripts was added to the world again: 
grafik
Changes in the HelpSystemEntry Prefab increase the size of the decor frame around the video player.

Some video were updated others are new. While trying to update videos some issue (#776 and #778) occurred. 
At the moment user gets an notification about the HelpSystem and how to enter it, that might be changed to something like #777. 

After approving this PR (especially how new entries are now created with a json file)  I can write a wiki entry on how to maintain this. 

It might be a good workflow to ask developers for new HelpEntries before merging PRs with new features to the master.

### CODE REVIEW

**Comment by falko17** [comment]
Note that the pipeline is currently failing because the help system videos aren't in LFS, even though they should be (due to their size). To fix this, we need to do an interactive rebase[^1], as they will otherwise be permanently in the history of the repository and will unnecessarily inflate it and slow it down. I recommend that we do this before the reviews, because otherwise the reviews will reference non-existing commits and would, for example, not be automatically applicable.

> After approving this PR (especially how new entries are now created with a json file) and I can write a wiki entry on how to maintain this.
> It might be a good workflow to ask developers for new HelpEntries before merging PRs with new features to the master.

I agree, both of these sound like good ideas. 
(Actually, for the latter, maybe it'd be nice to create a [PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with a checkboxed list, as many other open-source projects do, then we could also add some other common pitfalls in there, such as formatting, the git hook checks, etc. We can do this in a separate pull request.)

[^1]: Probably on commit 7032cad, which we want to `edit` to move those files into LFS.

**Comment by SarahAugustinowski** [comment]
> Note that the pipeline is currently failing because the help system videos aren't in LFS, even though they should be (due to their size). To fix this, we need to do an interactive rebase[1](#user-content-fn-1-55c1fc82bfca3929df64e2c481ccad8c), as they will otherwise be permanently in the history of the repository and will unnecessarily inflate it and slow it down. I recommend that we do this before the reviews, because otherwise the reviews will reference non-existing commits and would, for example, not be automatically applicable.

Can I specify the lfs-repo in the edit so the commit goes there instead? Or just delete the files? I would be happy to get some help with that :)

**Comment by falko17** [comment]
@SarahAugustinowski I took some time to fill in the relevant sections in our [Git FAQ](https://github.com/uni-bremen-agst/SEE/wiki/Git-FAQ) just now, which I totally forgot existed 😅

In your case, the relevant section is "How do I rebase a branch?" In the rebase, you will need to do an `edit` on commit 7032cad1dc0ff4c7935a335a317b655290d327f9. During the edit, you can add the moved files to LFS—see section "How do I add a large directory to LFS", in this case for directory `Assets/StreamingAssets/HelpSystem/Videos`.

If there are any issues or if anything is unclear, please message me on Mattermost, and I can help you on there.

**Comment by falko17** [comment]
Issues regarding LFS are resolved now, so the PR should be ready for review. (The pipeline is still failing, but this is due to https://github.com/game-ci/docker/issues/250 and happens on every PR right now.)

**Comment by SarahAugustinowski** [comment]
> Issues regarding LFS are resolved now, so the PR should be ready for review. (The pipeline is still failing, but this is due to [game-ci/docker#250](https://github.com/game-ci/docker/issues/250) and happens on every PR right now.)

thank you for your help! :) @falko17

**Comment by koschke** [comment]
"Hide node" is work in progress. No video and no text for this action.

**Comment by koschke** [comment]
In the video on "Show code" an error message appears because the issues cannot be dowloaded from the dashboard.

**Comment by koschke** [comment]
The help text is not automatically split into the existing line space. This way long help text will be truncated. The lower scroll bar has no effect.

**Comment by koschke** [comment]
> > @SarahAugustinowski It looks like the video `Assets\StreamingAssets\HelpSystem\Videos\Navigation.mp4` is showing the runtime configuration menu, but not the navigation.
> 
> @koschke There should not be any video at this path, it should be placed here: "\SEE\Assets\StreamingAssets\HelpSystem\Videos\Navigation\Navigation.mp4"

Sorry, I missed the directory. The path you gave was intended. Still, this video has the wrong content.

**Comment by koschke** [comment]
We will need to re-organize the structure of the help system content. Yet, that is beyond @SarahAugustinowski's task. We need to do that later.

**Comment by SarahAugustinowski** [comment]
> > > @SarahAugustinowski It looks like the video `Assets\StreamingAssets\HelpSystem\Videos\Navigation.mp4` is showing the runtime configuration menu, but not the navigation.
> > 
> > 
> > @koschke There should not be any video at this path, it should be placed here: "\SEE\Assets\StreamingAssets\HelpSystem\Videos\Navigation\Navigation.mp4"
> 
> Sorry, I missed the directory. The path you gave was intended. Still, this video has the wrong content.

Still weird :-D I have not pulled from the branch after the problems with lfs, but locally it is fine:
grafik

**Comment by SarahAugustinowski** [comment]
> "Hide node" is work in progress. No video and no text for this action.

Yep, the video should be updated after #776 is fixed.

**Comment by SarahAugustinowski** [comment]
> The help text is not automatically split into the existing line space. This way long help text will be truncated. The lower scroll bar has no effect.

The tick for horizontal scrolling was missing, the lower scrollbar works now.

**Pull request merged**
